Attribute VB_Name = "Module1"
Sub Format_date_MMMM_YY()
Attribute Format_date_MMMM_YY.VB_Description = "Use this macro to extract formated dates (MAR-21) from data "
Attribute Format_date_MMMM_YY.VB_ProcData.VB_Invoke_Func = "M\n14"
'
' Format_date_MMMM_YY Macro
' Use this macro to extract formated dates (MAR-21) from data
'
' Keyboard Shortcut: Ctrl+Shift+M
'
    ActiveCell.Offset(0, 2).Columns("A:A").EntireColumn.Select
    Selection.Replace What:="-", Replacement:="/", LookAt:=xlPart, _
        SearchOrder:=xlByRows, MatchCase:=False, SearchFormat:=False, _
        ReplaceFormat:=False, FormulaVersion:=xlReplaceFormula2
    ActiveCell.Offset(1, 0).Range("Table73[[#Headers],[DateInterview]]").Select
    Selection.End(xlDown).Select
    ActiveWindow.SmallScroll Down:=-3
    ActiveWindow.ScrollRow = 336
    ActiveWindow.ScrollRow = 335
    ActiveWindow.ScrollRow = 334
    ActiveWindow.ScrollRow = 332
    ActiveWindow.ScrollRow = 331
    ActiveWindow.ScrollRow = 329
    ActiveWindow.ScrollRow = 328
    ActiveWindow.ScrollRow = 326
    ActiveWindow.ScrollRow = 324
    ActiveWindow.ScrollRow = 323
    ActiveWindow.ScrollRow = 321
    ActiveWindow.ScrollRow = 320
    ActiveWindow.ScrollRow = 318
    ActiveWindow.ScrollRow = 315
    ActiveWindow.ScrollRow = 312
    ActiveWindow.ScrollRow = 307
    ActiveWindow.ScrollRow = 302
    ActiveWindow.ScrollRow = 297
    ActiveWindow.ScrollRow = 293
    ActiveWindow.ScrollRow = 289
    ActiveWindow.ScrollRow = 284
    ActiveWindow.ScrollRow = 279
    ActiveWindow.ScrollRow = 275
    ActiveWindow.ScrollRow = 270
    ActiveWindow.ScrollRow = 266
    ActiveWindow.ScrollRow = 262
    ActiveWindow.ScrollRow = 258
    ActiveWindow.ScrollRow = 254
    ActiveWindow.ScrollRow = 250
    ActiveWindow.ScrollRow = 246
    ActiveWindow.ScrollRow = 242
    ActiveWindow.ScrollRow = 237
    ActiveWindow.ScrollRow = 233
    ActiveWindow.ScrollRow = 229
    ActiveWindow.ScrollRow = 225
    ActiveWindow.ScrollRow = 222
    ActiveWindow.ScrollRow = 219
    ActiveWindow.ScrollRow = 216
    ActiveWindow.ScrollRow = 212
    ActiveWindow.ScrollRow = 209
    ActiveWindow.ScrollRow = 207
    ActiveWindow.ScrollRow = 205
    ActiveWindow.ScrollRow = 203
    ActiveWindow.ScrollRow = 201
    ActiveWindow.ScrollRow = 200
    ActiveWindow.ScrollRow = 198
    ActiveWindow.ScrollRow = 196
    ActiveWindow.ScrollRow = 194
    ActiveWindow.ScrollRow = 193
    ActiveWindow.ScrollRow = 192
    ActiveWindow.ScrollRow = 191
    ActiveWindow.ScrollRow = 190
    ActiveWindow.ScrollRow = 189
    ActiveWindow.ScrollRow = 188
    ActiveWindow.ScrollRow = 187
    ActiveWindow.ScrollRow = 186
    ActiveWindow.ScrollRow = 185
    ActiveWindow.ScrollRow = 184
    ActiveWindow.ScrollRow = 183
    ActiveWindow.ScrollRow = 182
    ActiveWindow.ScrollRow = 181
    ActiveWindow.ScrollRow = 180
    ActiveWindow.ScrollRow = 178
    ActiveWindow.ScrollRow = 177
    ActiveWindow.ScrollRow = 176
    ActiveWindow.ScrollRow = 175
    ActiveWindow.ScrollRow = 174
    ActiveWindow.ScrollRow = 173
    ActiveWindow.ScrollRow = 172
    ActiveWindow.ScrollRow = 171
    ActiveWindow.ScrollRow = 170
    ActiveWindow.ScrollRow = 169
    ActiveWindow.ScrollRow = 168
    ActiveWindow.ScrollRow = 167
    ActiveWindow.ScrollRow = 166
    ActiveWindow.ScrollRow = 165
    ActiveWindow.ScrollRow = 164
    ActiveWindow.ScrollRow = 163
    ActiveWindow.ScrollRow = 162
    ActiveWindow.ScrollRow = 161
    ActiveWindow.ScrollRow = 160
    ActiveWindow.ScrollRow = 158
    ActiveWindow.ScrollRow = 157
    ActiveWindow.ScrollRow = 155
    ActiveWindow.ScrollRow = 153
    ActiveWindow.ScrollRow = 151
    ActiveWindow.ScrollRow = 149
    ActiveWindow.ScrollRow = 148
    ActiveWindow.ScrollRow = 146
    ActiveWindow.ScrollRow = 143
    ActiveWindow.ScrollRow = 142
    ActiveWindow.ScrollRow = 139
    ActiveWindow.ScrollRow = 137
    ActiveWindow.ScrollRow = 135
    ActiveWindow.ScrollRow = 133
    ActiveWindow.ScrollRow = 130
    ActiveWindow.ScrollRow = 129
    ActiveWindow.ScrollRow = 127
    ActiveWindow.ScrollRow = 124
    ActiveWindow.ScrollRow = 122
    ActiveWindow.ScrollRow = 119
    ActiveWindow.ScrollRow = 116
    ActiveWindow.ScrollRow = 114
    ActiveWindow.ScrollRow = 111
    ActiveWindow.ScrollRow = 108
    ActiveWindow.ScrollRow = 106
    ActiveWindow.ScrollRow = 104
    ActiveWindow.ScrollRow = 102
    ActiveWindow.ScrollRow = 100
    ActiveWindow.ScrollRow = 98
    ActiveWindow.ScrollRow = 96
    ActiveWindow.ScrollRow = 94
    ActiveWindow.ScrollRow = 93
    ActiveWindow.ScrollRow = 91
    ActiveWindow.ScrollRow = 88
    ActiveWindow.ScrollRow = 86
    ActiveWindow.ScrollRow = 83
    ActiveWindow.ScrollRow = 80
    ActiveWindow.ScrollRow = 77
    ActiveWindow.ScrollRow = 74
    ActiveWindow.ScrollRow = 72
    ActiveWindow.ScrollRow = 71
    ActiveWindow.ScrollRow = 69
    ActiveWindow.ScrollRow = 68
    ActiveWindow.ScrollRow = 66
    ActiveWindow.ScrollRow = 65
    ActiveWindow.ScrollRow = 63
    ActiveWindow.ScrollRow = 62
    ActiveWindow.ScrollRow = 60
    ActiveWindow.ScrollRow = 59
    ActiveWindow.ScrollRow = 57
    ActiveWindow.ScrollRow = 56
    ActiveWindow.ScrollRow = 54
    ActiveWindow.ScrollRow = 53
    ActiveWindow.ScrollRow = 52
    ActiveWindow.ScrollRow = 51
    ActiveWindow.ScrollRow = 50
    ActiveWindow.ScrollRow = 48
    ActiveWindow.ScrollRow = 47
    ActiveWindow.ScrollRow = 45
    ActiveWindow.ScrollRow = 43
    ActiveWindow.ScrollRow = 41
    ActiveWindow.ScrollRow = 40
    ActiveWindow.ScrollRow = 38
    ActiveWindow.ScrollRow = 37
    ActiveWindow.ScrollRow = 35
    ActiveWindow.ScrollRow = 34
    ActiveWindow.ScrollRow = 32
    ActiveWindow.ScrollRow = 30
    ActiveWindow.ScrollRow = 29
    ActiveWindow.ScrollRow = 28
    ActiveWindow.ScrollRow = 27
    ActiveWindow.ScrollRow = 26
    ActiveWindow.ScrollRow = 25
    ActiveWindow.ScrollRow = 24
    ActiveWindow.ScrollRow = 23
    ActiveWindow.ScrollRow = 22
    ActiveWindow.ScrollRow = 21
    ActiveWindow.ScrollRow = 20
    ActiveWindow.ScrollRow = 19
    ActiveWindow.ScrollRow = 17
    ActiveWindow.ScrollRow = 16
    ActiveWindow.ScrollRow = 15
    ActiveWindow.ScrollRow = 14
    ActiveWindow.ScrollRow = 13
    ActiveWindow.ScrollRow = 11
    ActiveWindow.ScrollRow = 10
    ActiveWindow.ScrollRow = 9
    ActiveWindow.ScrollRow = 7
    ActiveWindow.ScrollRow = 6
    ActiveWindow.ScrollRow = 5
    ActiveWindow.ScrollRow = 4
    ActiveWindow.ScrollRow = 3
    ActiveWindow.ScrollRow = 2
    ActiveWindow.ScrollRow = 1
    ActiveCell.Offset(-376, 0).Range("Table73[[#Headers],[DateInterview]]").Select
    Range(Selection, Selection.End(xlDown)).Select
    Selection.NumberFormat = "[$-en-US]mmm-yy;@"
    ActiveCell.Select
End Sub
